name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Analyze, Format & Test
    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v6

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 📥 Get Dependencies
        run: flutter pub get

      - name: 📝 Check Formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: 🔍 Analyze Source Code
        run: flutter analyze

      - name: 🧪 Run Tests
        run: flutter test